### ISSUE TITLE
No audio after restarting stream (close & reconnect)

### ISSUE THREAD

**Issue by ktprograms** [shogo4405/HaishinKit.kt#131]
### Describe the bug

No audio in the stream after calling `connection.close()` and then `connection.connect(RTMP_URL)`. Works after restarting Activity (init-ing connection again).

### To Reproduce

1. Create `RtmpConnection` and `RtmpStream` with camera and audio source.
2. User presses button to stop streaming, which calls `connection.close()`.
3. User resumes streaming, code calls `connection.connect(RTMP_URL)` (`RTMP_URL` is a valid `rtmp://` URL, audio works on the first connection, but not this second one).

### Expected behavior

Audio should continue

### Version

0.10.4

### Smartphone info.

Android 12 (One UI 4.1)

### Additional context

Using nginx RTMP module as backend (and manually viewing recorded files on the server).

**Comment by shogo4405** [comment]
It works ok. Pixel3a(Android12), Pixel4a(Android13).
I think it's a Galaxy, I would like to know the specific model.
