### ISSUE TITLE
Typo in Jitpack Artifact location in README

### ISSUE THREAD

**Issue by isles1217** [shogo4405/HaishinKit.kt#176]
### Describe the bug

The jitpack artifact location is listed as 
`com.github.shogo4405:HaishinKit~kt:(...)` with a colon (":") separating the group from the module. This should be:
`com.github.shogo4405.HaishinKit~kt:(...)`  -- with a period (".") separating the artifcat group from the module.

In current README:
```
dependencies {
  implementation 'com.github.shogo4405:HaishinKit~kt:haishinkit:x.x.x'
  implementation 'com.github.shogo4405:HaishinKit~kt:vulkan:x.x.x'
}
```

### To Reproduce

In an Android project, attempt to import the HaishinKit dependency using the location provided:
```
dependencies {
  implementation 'com.github.shogo4405:HaishinKit~kt:haishinkit:0.11.0'
}
```

Result: package can't be resolved.

### Expected behavior

With a period separating the artifact group from the module, the package resolves:
```
dependencies {
  implementation 'com.github.shogo4405.HaishinKit~kt:haishinkit:0.11.0'
}
```

### Version

N/A

**Comment by shogo4405** [comment]
Thank you.
