### ISSUE TITLE
Audio and video out of sync

### ISSUE THREAD

**Issue by jrickett** [shogo4405/HaishinKit.kt#178]
### Describe the bug

Using HaishinKit to stream, when viewing the stream the audio and video appear to not be synced. From what I've observed the audio seems to be delayed anywhere from about 100ms to 1 second.

This happens on all devices I've tested, from both the example project in this repository, as well as my own app with using this library.

### To Reproduce

1. Run the example app on an Android device.
2. Tap the publish button
3. Watch the stream from a video player
4. The audio is delayed

### Expected behavior

The audio should be in sync with the video.

### Version

0.11.0

### Smartphone info.

- Device: Google Pixel 2XL
- OS: Android 11

- Device: Samsung Galaxy Tab A7 Lite
- OS: Android 13

- Device: Samsung Galaxy S20 FE 
- OS: Android 11

**Comment by shogo4405** [comment]
I would like to know the video and audio settings. Especially for video, only baseline is supported, and if main or high is used, it becomes asynchronous, causing issues. Additionally, I've heard that setting the audio to 48kHz can lead to synchronization problems.

**Comment by jrickett** [comment]
I'm just using the defaults at the moment, so 44.1kHz audio, and I think baseline for video? I'm just using the CameraTabFragment in the example app.

I've also tried the settings mentioned in the readme:

```
stream.audioSetting.bitRate = 32 * 1000

stream.videoSetting.width = 640
stream.videoSetting.height = 360
stream.videoSetting.bitRate = 160 * 1000
stream.videoSetting.IFrameInterval = 2
```

**Comment by shogo4405** [comment]
I confirmed audio synchronization issues when testing with nginx + ffplay.
