### ISSUE TITLE
The videoSetting.frameRate setting is not working.

### ISSUE THREAD

**Issue by AnthonyWu-kkstream** [shogo4405/HaishinKit.kt#220]
### Describe the bug

Hi, I've observed that the videoSetting.frameRate method's configuration is not effective in main branch. Additionally, the default frameRate you have set is 30, but the actual frameRate outputted in your FrameTracker is 60.

### To Reproduce

1.Open the sample app.
2.Set videoSetting.frameRate to 30.
3.Monitor the frameRate of the video status in the FrameTracker logs in Logcat.

### Expected behavior

1.Open the sample app.
2.Set videoSetting.frameRate to 30.
3.Monitor the frameRate of the video status in the FrameTracker logs in Logcat.

Expected frameRate is 30.

### Version

latest main branch

### Screenshots

![image](https://github.com/shogo4405/HaishinKit.kt/assets/143590617/9b4fdf6d-45de-4317-92a8-853688c6e77f)
![image](https://github.com/shogo4405/HaishinKit.kt/assets/143590617/e01f52f9-a14a-4d6b-a80e-73a82e512c3e)

**Comment by shogo4405** [comment]
Thank you for the report. It has been fixed.
