### ISSUE TITLE
Can u add appendBuffer () menthod

### ISSUE THREAD

**Issue by pqthong** [shogo4405/HaishinKit.kt#23]
**Is your feature request related to a problem? Please describe.**
I want to forward a video Stream to a VMS server, the video is captured by a different source and streamed to my phone via an HTTP connection, I want to forward it to a VMS Server
Right now I can see a method appendBuffer() available in swift, but it is not available in haishinkit.kt

**Describe the solution you'd like**
Can I use the haishinkits RTMP stream class to append a video buffer to stream to a VMS server, as well as append an audio buffer?

**Describe alternatives you've considered**
I have looked into the module but unable to find a method to stream out a buffer

**Additional context**
N/A

**Comment by shogo4405** [comment]
Thank you for request. I have no plan.
