### ISSUE TITLE
GLES10.glOrthof fail with error 0x502

### ISSUE THREAD

**Issue by chatelgu** [shogo4405/HaishinKit.kt#38]
**Describe the bug**
The test application always fails at start time on my phones. 

Adding some `GlUtil.checkGlError`, I find out that it's the call to `GLES10.glOrthof` line 133 of GlKernel.kt on last `main` branch that failed with error 0x502

https://github.com/shogo4405/HaishinKit.kt/blob/e8f42fa830d208b41e394b3dfa2662367ab6c4c9/haishinkit/src/main/java/com/haishinkit/graphics/gles/GlKernel.kt#L133

Skipping this line, the application is launching (the camera preview do not take all the phone screen and the image is not as clean as expected, but that's probably fair) 

**To Reproduce**
1. Launch the app
The application crash

**Expected behavior**
The application is not crashing

**Smartphone:**
 - Device: Pixel 6; OS: Android 12
 - Device: Samsung Galaxy S9; OS: Android 8.0.0

**Comment by shogo4405** [comment]
For sure. Thanks feedback. This is not good.
I can reproduce it. I'll see it.

**Comment by shogo4405** [comment]
I forgot what purpose I made. I removed it https://github.com/shogo4405/HaishinKit.kt/commit/495aeda1813724ba21c030226d00903866858746.
