### ISSUE TITLE
CAMERA_ERROR (3): submitRequestList - cannot use a surface that wasn't configured

### ISSUE THREAD

**Issue by digitalmidges** [shogo4405/HaishinKit.kt#4]
Hi, Iv'e tested the example app with 3 devices:

Samsung J7, Android version 8.1.0:
As soon as I click the "publish" button:
Screen freeze but the audio still working and broadcasting

Samsung 9+ , Android version 10:
As soon as I click the "publish" button:
Working but crashing after few minutes for unknown reason 

Xiaomi Mi A2 , Android version 10:
As soon as I click the "publish" button:
crash with this exception:
CAMERA_ERROR (3): submitRequestList - cannot use a surface that wasn't configured

Can you provide a workaround for this issue please?

**Comment by shogo4405** [comment]
This project is a work in progress. It's buggy.
It works for me the `feature/opengl-camera` branch.

Thank u.
