### ISSUE TITLE
Video aspect ratio still incorrect with some resolution settings

### ISSUE THREAD

**Issue by ktprograms** [shogo4405/HaishinKit.kt#56]
**Describe the bug**
Followup from #48, It works fine when not setting any resolution (so letting it use the default of 640x360), but when I add `cameraSource.resolution = Size(480, 640)` in the `onResume()` method of the example app's CameraTabFragment, both the view on the phone and the stream are stretched.

**To Reproduce**
1. Add `cameraSource.resolution = Size(480, 640)` in the `onResume()` method of the example app's CameraTabFragment
2. Hold phone in portrait mode
3. Tap publish
4. Open Stream
5. Both the video on the phone and the stream are stretched.

**Expected behavior**
Video should not be stretched

**Screenshots**
| Phone | VLC |
|--|--|
| <img src="https://user-images.githubusercontent.com/71804605/163120927-1dd0cec4-280c-463e-9936-299b282d855a.jpg"> | <img src="https://user-images.githubusercontent.com/71804605/163121041-03f610f4-a4ef-4032-b58a-9c335b6f6edd.jpg"> |

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - VLC media player 3.0.12.1 Vetinari (revision 3.0.12.1-0-g170157402b)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A02
 - OS: Android 11

**Comment by shogo4405** [comment]
Thank you feedback. i'm currently working to fix.
https://github.com/shogo4405/HaishinKit.kt/tree/feature/adjust-resolution
