### ISSUE TITLE
Please reset jitpack artifact

### ISSUE THREAD

**Issue by ktprograms** [shogo4405/HaishinKit.kt#72]
**Describe the bug**
Gradle can't use packages with dots in the name, so the library must be referred to as `HaishinKit~kt`. On the [JitPack page for the correctly named package](https://jitpack.io/#shogo4405/HaishinKit~kt), the `0.9.4` build failed. However, specifying the commit of the `0.9.4` tag in JitPack builds fine, so can you please delete the artifact so it can be rebuilt?

**To Reproduce**
1. Add `implementation 'com.github.shogo4405.HaishinKit~kt:haishinkit:0.9.4'` to a `build.gradle`

**Expected behavior**
Project can sync and build

**JitPack build log**
https://jitpack.io/com/github/shogo4405/HaishinKit~kt/0.9.4/build.log

**Build log of `0.9.4` commit**
https://jitpack.io/com/github/shogo4405/HaishinKit~kt/5bab74f/build.log

**Comment by shogo4405** [comment]
I did it. Thanks.
